version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - PORT=8080
    depends_on:
      - tests

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
