services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
    depends_on:
      - tests

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .env
